### ISSUE TITLE
Chat does not include assets using frappe docker installation instructions

### ISSUE THREAD

**Issue by ShaneAlexGraham** [frappe/chat#19]
When trying to install frappe as a production starting from https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps-for-production.md it does not include assets and I receive a 404 for all chat assets.

I have attempted to do exactly as the link below says:

(When building exactly as frappe docker suggests I only get the chat assets failing the frappe assets are fine)
![image](https://user-images.githubusercontent.com/27639949/142278562-8f481eba-065a-4313-a01f-1a9917569057.png)

I have also tried to build assets using bench (see current version below):

# Custom Nginx Docker File
```dockerfile
ARG IMAGE_TAG=latest
ARG DOCKER_REGISTRY_PREFIX=frappe
FROM ${DOCKER_REGISTRY_PREFIX}/bench:${IMAGE_TAG}

USER frappe

RUN git clone --depth 1 https://github.com/frappe/bench /tmp/bench \
    && sudo mkdir -p /var/www/error_pages \
    && sudo cp -r /tmp/bench/bench/config/templates /var/www/error_pages

RUN bench update
RUN bench init frappe-bench --skip-redis-config-generation
RUN cp -R --remove-destination /home/frappe/frappe-bench /home/frappe/frappe
RUN rm -rf /home/frappe/frappe-bench
RUN mv /home/frappe/frappe /home/frappe/frappe-bench

RUN cd frappe-bench && bench get-app https://github.com/frappe/chat
RUN cd frappe-bench && bench get-app https://github.com/frappe/bench_manager


FROM frappe/frappe-nginx:latest

COPY --from=0 /home/frappe/frappe-bench /home/frappe/frappe-bench
COPY --from=0 /var/www/error_pages /var/www/error_pages

RUN mkdir -p /var/www/html/sites
RUN ls /home/frappe \
    && ls /var/www/error_pages \
    && cp -R /home/frappe/frappe-bench/sites /var/www/html/sites

VOLUME [ "/assets" ]

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
```

# Custom Worker Dockerfile
```dockerfile
ARG IMAGE_TAG=latest
ARG DOCKER_REGISTRY_PREFIX=frappe
FROM ${DOCKER_REGISTRY_PREFIX}/bench:${IMAGE_TAG}

USER frappe

RUN git clone --depth 1 https://github.com/frappe/bench /tmp/bench \
    && sudo mkdir -p /var/www/error_pages \
    && sudo cp -r /tmp/bench/bench/config/templates /var/www/error_pages

RUN bench update
RUN bench init frappe-bench --skip-redis-config-generation
RUN cp -R --remove-destination /home/frappe/frappe-bench /home/frappe/frappe
RUN rm -rf /home/frappe/frappe-bench
RUN mv /home/frappe/frappe /home/frappe/frappe-bench

RUN cd frappe-bench && bench get-app https://github.com/frappe/chat
RUN cd frappe-bench && bench get-app https://github.com/frappe/bench_manager

ARG IMAGE_TAG=develop
ARG DOCKER_REGISTRY_PREFIX=frappe
FROM ${DOCKER_REGISTRY_PREFIX}/frappe-worker:${IMAGE_TAG}

COPY --from=0 /home/frappe/frappe-bench /home/frappe/frappe-bench

USER frappe
```

# Docker Compose
```
version: "3"

services:
  frappe-nginx:
    image: frappe-assets
    build:
      context: ../../build/frappe-nginx
    restart: on-failure
    environment:
      - FRAPPE_PY=frappe-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - SKIP_NGINX_TEMPLATE_GENERATION=${SKIP_NGINX_TEMPLATE_GENERATION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frappe-nginx.rule=Host(${SITES})"
      - "${ENTRYPOINT_LABEL}"
      - "${CERT_RESOLVER_LABEL}"
      - "traefik.http.services.frappe-nginx.loadbalancer.server.port=80"
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw

  frappe-python:
    image: frappe-worker
    build:
      context: ../../build/frappe-worker
    restart: on-failure
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw
      - assets-vol:/home/frappe/frappe-bench/sites/assets:rw

  frappe-socketio:
    image: frappe-socketio
    build:
      context: ../../build/frappe-socketio
    restart: on-failure
    depends_on:
      - redis-socketio
    extra_hosts:
    - "frappe.localhost:172.20.0.4"
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  frappe-worker-default:
    image: frappe-worker
    build:
      context: ../../build/frappe-worker
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  frappe-worker-short:
    image: frappe-worker
    build:
      context: ../../build/frappe-worker
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  frappe-worker-long:
    image: frappe-worker
    build:
      context: ../../build/frappe-worker
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw

  redis-cache:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-cache-vol:/data

  redis-queue:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-queue-vol:/data

  redis-socketio:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-socketio-vol:/data

  mariadb:
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql

  traefik:
    image: "traefik:v2.2"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "${HTTPS_REDIRECT_RULE_LABEL}"
      - "${HTTPS_REDIRECT_ENTRYPOINT_LABEL}"
      - "${HTTPS_REDIRECT_MIDDLEWARE_LABEL}"
      - "${HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert-vol:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    userns_mode: "host"

  site-creator:
    image: frappe-worker
    build:
      context: ../../build/frappe-worker
    restart: "no"
    command: new
    depends_on:
      - frappe-python
    environment:
      - SITE_NAME=${SITE_NAME}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_APPS=${INSTALL_APPS}
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  frappe-schedule:
    image: frappe-worker
    build:
      context: ../../build/frappe-worker
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

volumes:
  mariadb-vol:
  redis-cache-vol:
  redis-queue-vol:
  redis-socketio-vol:
  assets-vol:
  sites-vol:
  cert-vol:
  logs-vol:
```

No matter what I try I cannot get chat assets to add properly.
